
	#adminer
	server {
		listen 443 ssl;
		server_name adminer.npolack.42.fr;
		root /var/www/adminer;

		ssl_certificate /etc/nginx/ssl/server.crt;
		ssl_certificate_key /etc/nginx/ssl/server.key;

		location / {
			index index.php;
			try_files $uri $uri/ =404;
		}

		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_pass adminer:9000;
		}
	}

	# www.hazardous.fr
	server {
		# SSL/TLS Configuration
		listen 443 ssl;
		ssl_protocols TLSv1.3;
		ssl_certificate /etc/nginx/ssl/server.crt;
		ssl_certificate_key /etc/nginx/ssl/server.key;

		# root and index and server_name
		root /var/www/hazardous;
		server_name hazardous.fr;

		location / {
			index index.html index.htm;
			try_files $uri $uri/ =404;
		}

	}
