user nobody;
worker_processes auto;
pid /run/nginx.pid;
events {
    worker_connections 1024;
}




http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

	#redirect HTTP(80) -> HTTPS(443)
	server {
		listen 80;
		listen [::]:80;
		server_name npolack.42.fr hazardous.fr;

		return 301 https://$host$request_uri;
	}

	# www.hazardous.fr
	server {
		# SSL/TLS Configuration
		listen 443 ssl;
		ssl_protocols TLSv1.3;
		ssl_certificate /etc/nginx/ssl/server.crt;
		ssl_certificate_key /etc/nginx/ssl/server.key;

		# root and index and server_name
		root /var/www/hazardous;
		server_name hazardous.fr;

		location / {
			index index.html index.htm;
			try_files $uri $uri/ =404;
		}

	}

	# wordpress server
    server {
        # SSL/TLS Configuration
        listen 443 ssl;
        ssl_protocols TLSv1.3;
        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        # root and index and server_name
		root /var/www/wordpress;
        server_name npolack.42.fr;

		location / {
			index index.php index.html index.htm;
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_index index.php;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_pass wordpress:9000;
		}
    }

	server {
		listen 443 ssl;
		server_name adminer.npolack.42.fr;
		root /var/www/adminer;

		ssl_certificate /etc/nginx/ssl/server.crt;
		ssl_certificate_key /etc/nginx/ssl/server.key;

		location / {
			index index.php;
			try_files $uri $uri/ =404;
		}

		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_pass adminer:9000;
		}
	}
}
