version: "3.8"

services:
  nginx:
    container_name: nginx
    volumes:
      - "${HOST_VOLUME_PATH}/wordpress:/var/www/wordpress"
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
    image: nginx:ft42

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - "${HOST_VOLUME_PATH}/mariadb:/var/lib/mysql"
    restart: unless-stopped
    expose:
      - "3306"
    image: mariadb:ft42

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - "${HOST_VOLUME_PATH}/wordpress:/var/www/wordpress"
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"
    image: wordpress:ft42

networks:
  inception:
    name: inception
    driver: bridge
    attachable: true
    labels:
      com.docker.compose.network: "inception"
      com.docker.compose.project: "inception"
